# This just contains the jobs to call, the jobs are defined in the
# master branch.

# Configuration for this repository, determines which jobs to run.
- project:
    name: openstack/openstack-manuals
    templates:
      - openstack-manuals-build-translation
      - openstack-manuals-jobs
